---
platform: linux
inputs:
  - name: tracim-source
outputs:
  - name: pipeline
run:
  path: /bin/sh
  args:
    - -c
    - |
      cat
      tracim-source/concourse/pipelines/((pipeline))-header.yml
      tracim-source/concourse/pipelines/build-jobs.iyml
      > pipeline/((pipeline)).yml
